# docker-compose.yml
version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./laravel-app:/var/www/html
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
    volumes:
      - ./mysql-data:/var/lib/mysql